
name: Push to GCP

on:
  push:
    branches:
    - 'main'

permissions:
    id-token: write
    contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: confixa-rnd
        service_account_key: ${{ secrets.APP }}
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: confixa-rnd
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev
        docker build -t asia-south1-docker.pkg.dev/confixa-rnd/confixa-docker-images/abc:${{ github.sha }} .
        docker push asia-south1-docker.pkg.dev/confixa-rnd/confixa-docker-images/abc:${{ github.sha }}

    - name: Test Authentication
      run: git clone https://github.com/confixa/confixa-gitops.git
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Checkout Destination Repository
      uses: actions/checkout@v2
      with:
          repository: confixa/confixa-gitops  # Replace <destination-repo> with the destination repository's URL
          ref: confixa-gitops  # Specify the branch or tag you want to checkout
    
    - name: Verify Repository
      run: |
          ls -al
          cat confixa/confixa-gitops/blob/confixa-gitops/deployment.apps/dev-confixa-backend.yaml
          
    - name: Update Deployment File
      run: |
          # Update image file name in deployment.yaml using yq
          yq eval '.spec.containers[0].image |= sub("old-image-filename"; "new-image-filename")' confixa/confixa-gitops/blob/confixa-gitops/deployment.apps/dev-confixa-backend.yaml > confixa/confixa-gitops/blob/confixa-gitops/deployment.apps/dev-confixa-backend.yaml.tmp
          mv confixa/confixa-gitops/blob/confixa-gitops/deployment.apps/dev-confixa-backend.yaml.tmp confixa/confixa-gitops/blob/confixa-gitops/deployment.apps/dev-confixa-backend.yaml
    - name: Commit and Push Changes
      run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add path/to/deployment.yaml
          git commit -m "Update image file name in deployment file"
          git push https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
