name: Push to GCP

on:
  push:
    branches:
    - 'main'

permissions:
    id-token: write
    contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: confixa-rnd
        service_account_key: ${{ secrets.ADC }}
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: confixa-rnd
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/confixa-docker-images/abc
        docker build -t asia-south1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/confixa-docker-images/abc:latest .
        docker push asia-south1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/confixa-docker-images/abc:latest
