name: Push to GCP 

env:
  BRANCH1: ${{ vars.BRANCH }}

on: 
  push:
    branches:
      - ${{ vars.BRANCH }}

permissions:
  id-token: write
  contents: read
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Print env vars  
      run: |
        echo $BRANCH1
        echo ${{ vars.BRANCH }}
         
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v0
      with: 
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GAC }}
        export_default_credentials: true
        
    - name: Build and push image
      env:
        GOOGLE_PROJECT: ${{ secrets.PROJECT_ID }}  
      run: |
        gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev
        docker build -t ${{ secrets.GCR }}:${{ github.sha }} .
        docker push ${{ secrets.GCR }}:${{ github.sha }}
