'on':
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2
      - name: Setup pack CLI
        run: >

          wget -O /tmp/pack.tgz
          https://github.com/buildpacks/pack/releases/download/v0.24.0/pack-v0.24.0-linux.tgz


          tar -C $HOME -xzf /tmp/pack.tgz


          chmod +x $HOME/pack
      - name: Build Docker image with pack
        run: >

          $HOME/pack build dev-confixa-backend:${{ github.sha }} --builder
          gcr.io/buildpacks/builder
      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: ${{ secrets.PROJECT_ID}}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.PROJECT_ID}}
        run: >

          gcloud auth configure-docker asia-south1-docker.pkg.dev


          # docker build -t
          asia-south1-docker.pkg.dev/confixa-rnd/confixa-docker-images/dev-confixa-backend:${{
          github.sha }} .


          # docker push
          asia-south1-docker.pkg.dev/confixa-rnd/confixa-docker-images/dev-confixa-backend:${{
          github.sha }}
      - name: Tag Docker image
        run: >
          docker tag dev-confixa-backend:${{ github.sha }}
          asia-south1-docker.pkg.dev/confixa-rnd/confixa-docker-images/dev-confixa-backend:${{
          github.sha }}
      - name: Push Docker Image to Artifact Registry
        run: >
          docker push
          asia-south1-docker.pkg.dev/confixa-rnd/confixa-docker-images/dev-confixa-backend:${{
          github.sha }}


          git clone https://aniket-pharale:${{ secrets.TOKEN
          }}@github.com/confixa/confixa-gitops


          cd confixa-gitops


          git checkout confixa-gitops


          git config user.name "aniket-pharale"


          git config user.email "aniket.pharale@wohlig.com"


          # yq e '.spec.template.spec.containers[0].image =
          "asia-south1-docker.pkg.dev/confixa-rnd/confixa-docker-images/dev-confixa-backend:${{
          github.sha }}"' deployment.apps/deploy-confixa-backend.yaml >
          deployment.apps/deploy-confixa-backend.yaml


          yq e '.spec.template.spec.containers[0].image =
          "asia-south1-docker.pkg.dev/confixa-rnd/confixa-docker-images/dev-confixa-backend:${{
          github.sha }}"' -i deployment.apps/deploy-confixa-backend.yaml


          # yq e '.spec.template.spec.containers[0].image =
          "asia-south1-docker.pkg.dev/confixa-rnd/confixa-docker-images/dev-confixa-backend:${{
          github.sha }}"' -i deployment.apps/deploy-confixa-backend.yaml


          git add .


          git commit -m "updating newer image"  


          git push --set-upstream origin confixa-gitops
